      - name: Create Streamlit secrets (TOP-LEVEL, UPPERCASE)
        shell: bash
        run: |
          mkdir -p .streamlit
          cat > .streamlit/secrets.toml <<'EOF'
          APP_BASE_URL = "${{ secrets.APP_BASE_URL }}"

          EMAIL_HOST = "smtp.gmail.com"
          EMAIL_PORT = 587
          EMAIL_USERNAME = "fleetvamossla@gmail.com"
          EMAIL_PASSWORD = """${{ secrets.SMTP }}"""
          EMAIL_FROM = "fleetvamossla@gmail.com"
          EMAIL_USE_TLS = true
          EOF
          echo "Wrote .streamlit/secrets.toml with APP_BASE_URL and EMAIL_*"
