name: Deploy to Azure Web App (vamos-frotas-sla)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.11"
  APP_NAME: "vamos-frotas-sla"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x ".git/*" ".github/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: "production"
          package: "release.zip"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
