APP_BASE_URL = "https://seu-app.streamlit.app"

EMAIL_HOST = "smtp.office365.com"
EMAIL_PORT = 587
EMAIL_USERNAME = "seu-email@seu-dominio.com.br"
EMAIL_PASSWORD = "SENHA/APP_PASSWORD"
EMAIL_USE_TLS = true
EMAIL_FROM = "seu-email@seu-dominio.com.br"
